#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> [subdomain]
# Display information about subdomains.

domain_information () {
    # Fetch DNS record information
    ip=$(dig +short "$2"."$1")
    if [ -n "$ip" ]; then
        echo "$ip"
    else
        echo "No record found for $2.$1"
    fi
}

if [ "$#" -eq 1 ]; then
  # If only the domain is provided, check the default subdomains
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  # If both domain and subdomain are provided, check the specific subdomain
  domain_information "$1" "$2"
else
  # If the arguments are not as expected, display usage
  echo "Usage: $0 <domain> [subdomain]"
fi

