#!/usr/bin/env bash
# This script copy file from local to remote
if (("$#" != 4)); then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit 1
fi

file_path="$1"
ip="$2"
user_name="$3"
key_path="$4"
scp -i "$key_path" "$file_path" "$user_name@$ip:~/"
