#!/usr/bin/env bash
# > Install nginx on web-01 server
# > Nginx should be listening on port 80
# > Nginx should return 'Hello World!' when querying the server

# Check if nginx is installed by checking if the nginx binary exists
if [ ! -e /usr/sbin/nginx ]; then

    # Update the package list
    apt-get update

    # Install nginx
    apt-get -y install nginx

    echo "Nginx installed successfully."
else
    echo "Nginx is already installed."
fi

# Ensure the /var/www/html directory exists
if [ ! -e '/var/www/html' ]; then
    mkdir -p /var/www/html
fi

# Create the index.html file with "Hello World!" content
echo 'Hello World!' > /var/www/html/index.html

# Restart nginx to apply changes
service nginx restart

echo "Nginx installed and configured successfully."
