#!/usr/bin/env bash
# Program to install nginx on a server
# > Install nginx on your web-01 server
# > Nginx should be listening on port 80
# > Nginx should return 'Hello World!' when querying the server

# Update the package list
apt-get update

# Install nginx
apt-get -y install nginx

# Ensure the /var/www/html directory exists
if [ ! -e '/var/www/html' ]; then
    mkdir -p /var/www/html
fi

# Create the index.html file with "Hello World!" content
echo 'Hello World!' > /var/www/html/index.html

# Make sure the Nginx configuration points to the default root directory
sed -i 's@root /var/www/html@root /var/www/html@g' /etc/nginx/sites-enabled/default

# Stop Apache if it's running
systemctl stop apache2
systemctl disable apache2

# Restart nginx to apply changes
systemctl restart nginx

echo "Nginx installed and configured successfully."
