#!/usr/bin/env bash
# > Configure Nginx server to have a custom 404 page
# > that contains the string Ceci n'est pas une page.


apt-get update
apt-get -y install nginx

mkdir -p /var/www/html

# Prepare the custom file
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo 'Hello World!' > /var/www/html/index.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By \$hostname;

        root /var/www/html;
        index index.html index.htm;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /redirect_me {
                return 301 https://youtube.com/;
        }

        error_page 404 /404.html;

        location = /404.html {
                internal;
        }
}" > /etc/nginx/sites-available/default;

service nginx restart;
