#!/usr/bin/env bash
# Install and configerring nginx web server with header

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '/listen [::]:80 default_server;/a add_header X-Served-By \$hostname;' \
/etc/nginx/sites-available/default
sudo service nginx restart
