#!/usr/bin/env bash
# Script to install and configure HAProxy on a new Ubuntu machine

# Update package list and install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Create HAProxy configuration
echo "global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

backend web-backend
    balance roundrobin
    server web-01 54.165.77.76:80 check
    server web-02 34.239.248.129:80 check

frontend http
    bind *:80
    mode http
    default_backend web-backend" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Start HAProxy service
sudo service haproxy start

# Check if HAProxy is running correctly
if systemctl is-active --quiet haproxy; then
    echo "HAProxy installed and configured successfully."
else
    echo "HAProxy failed to start. Check the configuration and try again."
fi
