#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

# Check if password is passed as an argument.
if [ -z "$1" ]; then
     echo "Usage: $0 <mysql_root_password>"
     exit 1
fi

# Generate the MySQL dump
mysqldump --all-databases -u root --password="$1" > backup.sql

# Get the current date in the required format
today=$(date +"%d-%m-%y")

# Create a gzip compressed archive of the MySQL dump
gzip -c backup.sql > "$today.tar.gz"
