#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

# Path to the /etc/passwd file
passwd_file="/etc/passwd"

# Check if the file exists
if [ ! -e "$passwd_file" ]; then
    echo "Error: /etc/passwd file not found."
    exit 1
fi

# Read the file line by line using a for loop
while read -r line; do
	# Extract fields to a var
	username=$(echo "$line" | cut -d':' -f1) # Username is in f1 of file
	uid=$(echo "$line" | cut -d':' -f2) # User id is in f2
	home=$(echo "$line" | cut -d':' -f6)

	# Display username, user id, and home directory
	echo "$username:$uid:$home"
done < $passwd_file

