#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS

file="/etc/passwd"

# Check if file exist
if [ ! -e "$file" ]; then
	echo "Error: File does not exist"
	exit 1
fi

IFS=:
while read -r username pw uid gid uid_info home cmd; do
		echo "The user $username is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pw, more info about the user here: $uid_info"
done < "$file"
