#!/usr/bin/env bash
# This script display "Best School" 9 times
# Display "Hi" on the 9th time

i=1
while [ $i -le 10 ]; do
        if [ $i -eq 9 ]
	then
                echo "Hi"
        else
                echo "Best School"
        fi
        ((i++))
done
