#!/usr/bin/env bash
# This script that gives you information about the school file

file="school"

# Check if file "school" exist
if [ -e $file ]; then
	echo "school file exists"
	# Check if school file is empty
	if [ -s $file ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	# Check if file is a regular file
	if [ -f $file ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
